###################################################
# Name: Snakefile
# Description: Main workflow for project ...
# Date: 1/8/22
###################################################

import glob
import os
import shutil
import random

# Import configuration, and needed parameters
configfile: "config/config.yaml"

num_datasets = config["NUM_DATASETS"]
base_dir = config["DATA_ROOT"]
exp_type = config["EXP_TYPE"]
k_values = ["7","9","11","13","15","17","21","23","25","27","29","31","33","35","37"]

###############################################################################
# IMPORTANT: Sets the working directory based on configuration parameter, and 
#            it can be set on command-line using --config DATA_ROOT=""
###############################################################################
workdir: config["DATA_ROOT"]

###############################################################################
# Imports rules for each type of experiment
###############################################################################

include: "rules/exp_type_1.smk"
include: "rules/exp_type_2.smk"

rule all:
    input:
        "within_dataset_analysis/within_dataset_analysis.csv",
        "across_dataset_analysis/across_dataset_analysis.csv"









