###################################################
# Name: Snakefile
# Description: Main workflow for project ...
# Date: 1/8/22
###################################################

import glob
import os
import shutil
import random

# Import configuration, and needed parameters
configfile: "config/config.yaml"

num_datasets = config["NUM_DATASETS"]
base_dir = config["WORK_ROOT"]
database_root = config["DATABASE_ROOT"]
num_trials = config["NUM_TRIALS"]
curr_trial = config["CURR_TRIAL"]
repo_dir = config["REPO_DIRECTORY"]
exp_type = config["EXP_TYPE"]
num_reads_per_dataset =  config["NUM_READS_PER_DATASET"]
pbsim_model = config["PBSIM_MODEL"]
thresh = config["THRESHOLD"]
r_dir = config["RINDEX_BUILD_DIRECTORY"]
trial_info_dir = config["TRIAL_INFO_DIR"]
num_kmers = config["KMERS_PER_DATASET"]
num_of_non_kmers = config["NON_KMERS_PER_DATASET"] # meaning either MEMs or half-MEMs

out_pivot_exp4 = config["OUT_PIVOT"]

#k_values = [str(x) for x in range(7, 31, 1)] + [str(x) for x in range(34, 50, 3)]
k_values = [str(x) for x in range(7, 31, 6)]

t_values = [1] + [str(x) for x in range(5, 35, 5)]

###############################################################################
# IMPORTANT: Sets the working directory based on configuration parameter, and 
#            it can be set on command-line using --config WORK_ROOT=""
###############################################################################
workdir: config["WORK_ROOT"]

###############################################################################
# Imports rules for each type of experiment
###############################################################################

include: "rules/prepare_data.smk"
include: "rules/exp_type_1.smk"
include: "rules/exp_type_2.smk"
include: "rules/exp_type_3.smk"
include: "rules/exp_type_4.smk"
include: "rules/exp_type_5.smk"
include: "rules/exp_type_6.smk"
include: "rules/exp_type_7.smk"
include: "rules/exp_type_8.smk"

# Rule all for exp 2 and 3
#rule all:
#    input:
#        "within_dataset_analysis/within_dataset_analysis.csv",
#        "across_dataset_analysis/across_dataset_analysis.csv"

# Rule all for exp 4
#rule all:
#    input:
#        "accuracies/accuracy_scores.csv"

# Rule all for exp 5
#rule all:
#    input:
#        "output_type_8/half_mems/confusion_matrix.csv",
#        "output_type_8/mems/confusion_matrix.csv"

# Rule all for exp 7
#rule all:
#    input:
#        "output_type_7/half_mems/illumina/confusion_matrix.csv",
#        "output_type_7/mems/illumina/confusion_matrix.csv",
#        "output_type_7/half_mems/ont/confusion_matrix.csv",
#        "output_type_7/mems/ont/confusion_matrix.csv"